import matplotlib.pyplot as plt
from PIL import Image
import numpy as np
# perlin4000x4000.binary is generated by Perlin.c
filename = '/tmp/perlin4000x4000.binary' #float number on each line, these numbers are Perlin Noise

f = open(filename, 'r')

w, h = 256, 256
data = np.zeros((h, w, 3), dtype=np.uint8)
result = []
for i in range(w): #Make one common list with 4000 lists inside, each list contains 4000 float numbers
    tmp = []
    for j in range(h):
        float_line = float(f.readline()[:-1])
        tmp.append(float_line)
        if float_line > 0.5:
         data[i, j] = [0, 255 * float_line, 0]
        else:
         data[i, j] = [0, 0, 256 * float_line]
    result.append(tmp)

plt.imshow(result, cmap='gray')
plt.savefig('/tmp/perlin_noise.png')
plt.show()

img = Image.fromarray(data, 'RGB')
img.save('my.png')
